- log:
    project: "DeepPilco"

- train:
    T: 25
    K: 10
    input_size_dynamic: 5
    output_size_dynamic: 4
    hidden_size_dynamic: 64
    hidden_layer_dynamic: 3
    dropout_training_dynamic: 0.1
    dropout_sampling_dynamic: 0.5
    input_size_polciy: 4
    output_size_policy: 2
    hidden_size_dynamic: 64
    hidden_layer_dynamic: 3
    dropout_training_dynamic: 0.05
    batch_size: 4

- env:
    init_mean_position: [0, 0, 0, 0]
    init_std_position: [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    l1: 1
    cost_sigma : 1



