- log:
    project: "DeepPilco"

- train:
    T: 25
    K: 10
    input_size_dynamic: 12
    output_size_dynamic: 11
    hidden_size_dynamic: 64
    hidden_layer_dynamic: 3
    dropout_training_dynamic: 0.05
    dropout_sampling_dynamic: 0.5
    input_size_policy: 11
    output_size_policy: 1
    hidden_size_policy: 64
    hidden_layer_policy: 3
    dropout_training_policy: 0.05
    batch_size: 4
    discount: 1
    epsilon: 0.00001

- env:
    init_mean_position: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    init_std_position: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    l1: 1
    l2: 1
    cost_sigma : 1



